import{a as m,S as p,i as s}from"./assets/vendor-bbAy8n95.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function r(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(o){if(o.ep)return;o.ep=!0;const a=r(o);fetch(o.href,a)}})();const u=async(e,t=1)=>{const r={key:"48862284-111645087e0508ab98b21d672",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await m.get("https://pixabay.com/api/",{params:r})).data}catch(l){throw new Error(l)}},i=document.querySelector(".gallery");i||console.error("Gallery container not found!");let g=new p(".gallery a",{captionsData:"alt",captionDelay:250});const h=e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}" class="gallery-link">
        <img src="${e.webformatURL}" alt="${e.tags}" width="360" class="gallery-img" loading="lazy"/>
      </a>
      <ul class="gallery-info-list">
        <li><h3>Likes</h3><p>${e.likes}</p></li>
        <li><h3>Views</h3><p>${e.views}</p></li>
        <li><h3>Comments</h3><p>${e.comments}</p></li>
        <li><h3>Downloads</h3><p>${e.downloads}</p></li>
      </ul>
    </li>`,y=e=>{if(!i)return;if(e.length===0){console.warn("No images to render.");return}const t=document.createDocumentFragment(),r=document.createElement("div");for(r.innerHTML=e.map(h).join("");r.firstChild;)t.appendChild(r.firstChild);i.appendChild(t),g.refresh()},b=()=>{i&&(i.innerHTML="")},w=document.querySelector(".form");document.querySelector(".gallery");const f=document.querySelector(".load-more-btn");let c="",n=1;const C=async e=>{e.preventDefault();const t=document.querySelector(".loader-container");if(t.style.display="block",c=e.currentTarget.elements.query.value.trim(),c===""){t.style.display="none",s.error({message:"Please complete the form",messageColor:"#fafafb",icon:"fas fa-keyboard",position:"topRight",backgroundColor:"#ef4040",color:"#fafafb"});return}try{const r=await u(c,n);if(r.totalHits===0){s.error({message:"Sorry, no images match your query.",messageColor:"#fafafb",icon:"far fa-file-image",position:"topRight",backgroundColor:"#ef4040",color:"#fafafb"});return}b(),y(r.hits),r.totalHits>n*15?f.style.display="block":f.style.display="none"}catch{s.error({message:"Something went wrong",messageColor:"#fafafb",icon:"fas fa-exclamation-triangle",position:"topRight",backgroundColor:"#ef4040",color:"#fafafb"})}finally{t.style.display="none"}e.target.reset()},S=async()=>{var t;n+=1;const e=document.querySelector(".loader-container");e.style.display="block";try{const r=await u(c,n);y(r.hits),r.totalHits<=n*15&&(f.style.display="none",s.info({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fafafb",icon:"far fa-file-image",position:"topRight",backgroundColor:"#ef4040",color:"#fafafb"}));const l=((t=document.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:l*2,behavior:"smooth"})}catch{s.error({message:"Something went wrong",messageColor:"#fafafb",icon:"fas fa-exclamation-triangle",position:"topRight",backgroundColor:"#ef4040",color:"#fafafb"})}finally{e.style.display="none"}};w.addEventListener("submit",C);f.addEventListener("click",S);
//# sourceMappingURL=index.js.map
