import{a as m,S as p,i as s}from"./assets/vendor-bbAy8n95.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const u=async(e,r=1)=>{const o={key:"48862284-111645087e0508ab98b21d672",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};try{return(await m.get("https://pixabay.com/api/",{params:o})).data}catch(l){throw new Error(l)}},i=document.querySelector(".gallery");i||console.error("Gallery container not found!");let h=new p(".gallery a",{captionsData:"alt",captionDelay:250});const b=e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}" class="gallery-link">
        <img src="${e.webformatURL}" alt="${e.tags}" width="360" class="gallery-img" loading="lazy"/>
      </a>
      <ul class="gallery-info-list">
        <li><h3>Likes</h3><p>${e.likes}</p></li>
        <li><h3>Views</h3><p>${e.views}</p></li>
        <li><h3>Comments</h3><p>${e.comments}</p></li>
        <li><h3>Downloads</h3><p>${e.downloads}</p></li>
      </ul>
    </li>`,y=e=>{if(!i)return;if(e.length===0){console.warn("No images to render.");return}const r=document.createDocumentFragment(),o=document.createElement("div");for(o.innerHTML=e.map(b).join("");o.firstChild;)r.appendChild(o.firstChild);i.appendChild(r),h.refresh()},g=()=>{i&&(i.innerHTML="")},w=document.querySelector(".form");document.querySelector(".gallery");const c=document.querySelector(".load-more-btn");let f="",n=1;const C=async e=>{e.preventDefault();const r=document.querySelector(".loader-container");if(r.style.display="block",f=e.currentTarget.elements.query.value.trim(),n=1,c.style.display="none",f===""){r.style.display="none",s.error({message:"Please complete the form",messageColor:"#fafafb",icon:"fas fa-keyboard",position:"topRight",backgroundColor:"#ef4040",color:"#fafafb"});return}try{const o=await u(f,n);if(g(),o.hits.length===0){s.error({message:"Sorry, no images match your query.",messageColor:"#fafafb",icon:"far fa-file-image",position:"topRight",backgroundColor:"#ef4040",color:"#fafafb"});return}y(o.hits),o.totalHits>n*15&&(c.style.display="block")}catch{s.error({message:"Something went wrong",messageColor:"#fafafb",icon:"fas fa-exclamation-triangle",position:"topRight",backgroundColor:"#ef4040",color:"#fafafb"})}finally{r.style.display="none"}e.target.reset()},S=async()=>{var r;n+=1;const e=document.querySelector(".loader-container");e.style.display="block",c.style.display="none";try{const o=await u(f,n);if(o.hits.length===0){g(),s.info({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fafafb",icon:"far fa-file-image",position:"topRight",backgroundColor:"#ef4040",color:"#fafafb"});return}y(o.hits),o.totalHits>n*15?c.style.display="block":s.info({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fafafb",icon:"far fa-file-image",position:"topRight",backgroundColor:"#ef4040",color:"#fafafb"});const l=((r=document.querySelector(".gallery-item"))==null?void 0:r.getBoundingClientRect().height)||0;window.scrollBy({top:l*2,behavior:"smooth"})}catch{s.error({message:"Something went wrong",messageColor:"#fafafb",icon:"fas fa-exclamation-triangle",position:"topRight",backgroundColor:"#ef4040",color:"#fafafb"})}finally{e.style.display="none"}};w.addEventListener("submit",C);c.addEventListener("click",S);
//# sourceMappingURL=index.js.map
